from checkBlast import blast_check
from patho import patho_check
import pandas as pd

def final_check(sequence: str) -> None:

    result = blast_check(sequence)
    if not result:
        return
    
    # pathoLM
    result = patho_check(sequence)
    if result:
        return

    print(f'\nFinal sequence: {sequence}\n')

if __name__ == "__main__":
    GENERATIONS = "sequence_recovery_results/output1.parquet"
    generations = pd.read_parquet(GENERATIONS)

    #generate sequence
    sequence1 = "AGAGTTTGATCCTGGCTCAGGACGAACGCTGGCGGCGTGCCTAATATGCTTAAGCATGAAGTGTGGCGAACGGGTGAGTAACGCGTGAGCAACCTGCCCTTAGGACTGAGAGATGGCGACGGGCGGTCCAATCCGAACTGAGCCACGCCGCAAGGCCAAAACTCTATCAGTAGCGGGCGACTGAGAGGTTGTCGACGTTACTCTGAGAGGGCGAAAAA"
    sequence2 = "tgatttgccagcacttttcaaagggtattataaagagccagaacgtacggcgaaagcgcaaacaggtaaatactacatcactggtgacttagctcatgtagatgatgatggttatttctggtttgaaggacgtcgagatgacattattattagttcaggctatacgattgggccttttgaagttgaggatgcgttaacgaatcatccagccgttaaagaatgtgctgtagtagcaaaacctcatgatatacgaggaaatattgttaaagcattcgttattttacaggatcatactgcggctaatgatacgctagttaaagaactacaacaatttgttaaaaatgaagttgcaccatataaatatccgagagagattgaattcgttgacgacttaccaaaaacaaactcaggtaaaattcgtcgtgttgaactacgagatgctgaaatagaaaaatggcaacaacaaaaagatagcaatcaataaacatagtaaagcagtccaatgcgtaaggcatgatgatacgcactggactgcttgtttatttatgatgttctttgtcgtctagttataaatattaaaattagtttagaaacaagcgcaaccagtattaagaatgagaaaatataagatgttaaacctcgaatatcccagtttaataaaaacacattactatcaccggcattaagttgaaactcagtatgtgttagaacgataattacaatacctataagggcaagattcaaaataaatttcaatattaaaggtaattgaagtgattttcttagatgcatatattgaatctcctttttatgattgattttacacttatattgtatcaaaatagagtatatgtttaaaatgctataagtcaaatgtagattaaaacaatcgttagctatttgttgtcaaataattatgattgatttgatatttatcttctatgaataaaagatttaatatattgcaaagttaatgaataattataatttacatttaccactgcttgctttaacatatatatgtaagcactaactatagtattttgttacagcgtatcaattaaaacaggaagttatctatggcgttgatattttaaagaaatatgtcagttttatgtaactttcatattgatgatacacatttacaatttttggagaggtgaaaccaatggctaagtctaatagtaaagacatcgttttaattggagccggtgtacttagcacaacatttggttcaatgttaaaagaaattgagccagactggaatatccacgtttacgaacgcttggatcgtcctgcaatcgaaagttcaaacgaaagaaataatgctggtacgggtcatgcagcattatgtgagttgaactacacagttttacaacctgatggttctatcgacatcgaaaaagcgaaagtgattaacgaagagtttgagatttcaaaacaattctggggtcacttagtgaaaagcggtaacatcgagaacccaagagaatttatcaatccattaccacacatcagttatgttagaggtaaaaacaatgttaaattcttaaaagatcgttacgaagcgatgaaagctttccctatgttcgataatatcgaatatactgaagacatcgaagtaatgaaaaaatggattccattgatgatgaaaggccgtgaagataaccctggtatcatggcggcaagtaaaattgacgaaggtacagatgtaaacttcggtgaattaacacgtaaaatggctaaaagcattgaagcacatccaaatgctacagtgcaatttaaccatgaagttgttgattttgaacaattatcaaatggtcaatgggaagttactgttaaaaatcgcctaactggtgagaaattcaaacaagtaactgactatgtattcatcggtgctggcggtggagcaattccattattacaaaaaacaggtatccctgaaagtgaacatttaggtggattccctatcagtggtcaattcttagcttgtacaaacc"
    
    for index, row in generations.iterrows():
        final_check(row['pred'])

    final_check(sequence1)
    final_check(sequence2)